[package]
name = "toml-cli"
version = "0.1.0"
authors = ["Greg Price <gnprice@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "toml"
path = "src/main.rs"

[dependencies]
failure = "0.1"
regex = "1"
serde = "1.0"
serde_json = "1.0"
structopt = "0.3"
toml_edit = "0.1"
